language: python
sudo: required
services:
  - mongodb
python:
  - '3.6'
before_install:
  - npm install aglio
install:
  - pip install -r requirements/requirements.txt -r tests/requirements.txt
  - npm install -g dredd@5.1.4 --no-optional
before_script:
  - python setup.py install
env:
  global:
    - HISTORY_DB_ADDRESS: "localhost"

script:
  - docker build -t history -f ./docker/history.docker .
  - docker build -t persister -f ./docker/persister.docker .
  - ./tests/start-test.sh
after_success:
  - travis/publish.sh
  - travis/deploy-gh-pages.sh
